name: ANUPQ
version: 3.2
date: 2017-11-29
description: |
    ANU p-Quotient

authors:
    - name: Greg Gamble
      url: http://school.maths.uwa.edu.au/~gregg
    - name: Werner Nickel
      url: http://www.mathematik.tu-darmstadt.de/~nickel/
    - name: Eamonn O'Brien
      url: http://www.math.auckland.ac.nz/~obrien

maintainers:
    - name: Greg Gamble
      url: http://school.maths.uwa.edu.au/~gregg
    - name: Max Horn
      url: http://www.quendi.de/math

GAP: ">= 4.8"

needed-pkgs:
    - name: "autpgrp"
      version: ">=1.5"
      url: "https://gap-packages.github.io/autpgrp/"

www: https://gap-packages.github.io/anupq/
readme: README
packageinfo: https://gap-packages.github.io/anupq/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/anupq/releases/download/v3.2/anupq-3.2.tar.gz
    - name: .tar.bz2
      url: https://github.com/gap-packages/anupq/releases/download/v3.2/anupq-3.2.tar.bz2

abstract: |
    The <span class="pkgname">ANUPQ</span> package provides an interactive    interface to the p-quotient, p-group generation and standard presentation    algorithms of the ANU pq C program.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
