name: ANUPQ
version: 3.1.3
date: 10/01/2016
description: ANU p-Quotient

authors:
    - name: Greg Gamble
      url: http://school.maths.uwa.edu.au/~gregg
    - name: Werner Nickel
      url: http://www.mathematik.tu-darmstadt.de/~nickel/
    - name: Eamonn O'Brien
      url: http://www.math.auckland.ac.nz/~obrien

maintainers:
    - name: Greg Gamble
      url: http://school.maths.uwa.edu.au/~gregg
    - name: Max Horn
      url: http://www.quendi.de/math

GAP: ">= 4.5"

needed-pkgs:
    - name: "autpgrp"
      version: ">=1.5"
      url: "http://www.icm.tu-bs.de/~beick/so.html"

www: http://gap-packages.github.io/anupq/
readme: http://gap-packages.github.io/anupq/README
packageinfo: http://gap-packages.github.io/anupq/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/anupq/releases/download/v3.1.3/anupq-3.1.3.tar.gz
    - name: .tar.bz2
      url: https://github.com/gap-packages/anupq/releases/download/v3.1.3/anupq-3.1.3.tar.bz2

abstract: The <span class="pkgname">ANUPQ</span> package provides an interactive    interface to the p-quotient, p-group generation and standard presentation    algorithms of the ANU pq C program.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
